# ---------------------------------------------------------------------------
# Custom Docker image for Azure Functions on Container Apps (Python 3.12)
# Includes GDAL, rasterio, and Fiona built from source for KML/raster ops.
# ---------------------------------------------------------------------------
# Stage 1: Build GDAL and Python geospatial wheels
# ---------------------------------------------------------------------------
ARG BUILDER_BASE_IMAGE=mcr.microsoft.com/azure-functions/python:4-python3.12
ARG RUNTIME_BASE_IMAGE=mcr.microsoft.com/azure-functions/python:4-python3.12
ARG GEO_DEPS_PREINSTALLED=false
FROM ${BUILDER_BASE_IMAGE} AS builder

# Install system dependencies for building GDAL, Fiona, rasterio
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libxml2-dev \
    libxslt1-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set GDAL config for pip builds
ENV GDAL_CONFIG=/usr/bin/gdal-config

# Install Python dependencies into a target directory for copying
RUN mkdir -p /build /home/site/wwwroot/.python_packages/lib/site-packages \
    && chown -R app:app /build /home/site/wwwroot

USER app

COPY --chown=app:app requirements.txt /tmp/requirements.txt
ARG GEO_DEPS_PREINSTALLED
RUN if [ "$GEO_DEPS_PREINSTALLED" = "true" ]; then \
            grep -Evi '^(fiona|lxml|shapely|pyproj|rasterio)($|[<>=~!])' /tmp/requirements.txt > /tmp/requirements.runtime.txt; \
        else \
            cp /tmp/requirements.txt /tmp/requirements.runtime.txt; \
        fi && \
        pip install --no-cache-dir --no-compile --target=/home/site/wwwroot/.python_packages/lib/site-packages \
        -r /tmp/requirements.runtime.txt
# Copy application code
WORKDIR /build
COPY --chown=app:app host.json /build/
COPY --chown=app:app function_app.py /build/
COPY --chown=app:app kml_satellite/ /build/kml_satellite/

# Note: Python v2 function metadata (.azurefunctions/) is auto-generated by the
# Azure Functions runtime at startup; no build-time metadata generation needed.


# ---------------------------------------------------------------------------
# Stage 2: Runtime image
# ---------------------------------------------------------------------------
FROM ${RUNTIME_BASE_IMAGE}

# Install only the runtime GDAL/GEOS/PROJ libraries (no build tools).
# Python wheels for rasterio/fiona/pyproj/shapely include their native
# dependencies under *.libs, so avoid installing heavyweight gdal-bin here.
# Keep only minimal XML libs required by lxml/Fiona runtime behavior.
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2 \
    libxslt1.1 \
    && rm -rf /var/lib/apt/lists/*

LABEL org.opencontainers.image.source="https://github.com/Hardcoreprawn/azure-workflow-for-kml-satellite" \
      org.opencontainers.image.description="KML Satellite Imagery Pipeline — Azure Functions on Container Apps"

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    GDAL_DATA=/usr/share/gdal \
    PROJ_DATA=/usr/share/proj \
    PYTHONDONTWRITEBYTECODE=1

# Copy installed Python packages from builder
COPY --from=builder --chown=app:app /home/site/wwwroot/.python_packages /home/site/wwwroot/.python_packages

# Copy application code and required files from builder
COPY --from=builder --chown=app:app /build/host.json /home/site/wwwroot/
COPY --from=builder --chown=app:app /build/function_app.py /home/site/wwwroot/
COPY --from=builder --chown=app:app /build/kml_satellite/ /home/site/wwwroot/kml_satellite/

# Remove bytecode and interpreter caches that do not provide runtime value.
RUN find /home/site/wwwroot/.python_packages /home/site/wwwroot/kml_satellite \
    -type d -name '__pycache__' -prune -exec rm -rf '{}' + \
    && find /home/site/wwwroot/.python_packages /home/site/wwwroot/kml_satellite \
    -type f \( -name '*.pyc' -o -name '*.pyo' \) -delete

USER app

# Fail build early if runtime native deps are unresolved.
RUN python -c "import rasterio, fiona, pyproj, shapely"
