from datetime import datetime
from typing import Any

from azure.durable_functions.models.OrchestrationRuntimeStatus import (
    OrchestrationRuntimeStatus,
)

class DurableOrchestrationStatus:
    @property
    def instance_id(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def runtime_status(self) -> OrchestrationRuntimeStatus | None: ...
    @property
    def created_time(self) -> datetime | None: ...
    @property
    def last_updated_time(self) -> datetime | None: ...
    @property
    def custom_status(self) -> Any: ...
    @property
    def output(self) -> Any: ...
    @property
    def input(self) -> Any: ...
    @property
    def history(self) -> list[Any] | None: ...
    def __bool__(self) -> bool: ...
