class RetryOptions:
    def __init__(
        self,
        first_retry_interval_in_milliseconds: int,
        max_number_of_attempts: int,
    ) -> None: ...
    @property
    def first_retry_interval_in_milliseconds(self) -> int: ...
    @property
    def max_number_of_attempts(self) -> int: ...
    def to_json(self) -> dict[str, str | int]: ...
