"""Audit-grade EUDR evidence PDF builder and helpers (#587)."""

from typing import Any

from blueprints.export.csv import _as_dict
from blueprints.export.pdf import _safe_text
from treesight.constants import EUDR_CUTOFF_DATE

_EUDR_CUTOFF_YEAR = 2021  # Post-31 December 2020


def _audit_cover_page(pdf: Any, manifest: dict[str, Any], instance_id: str) -> None:
    """Write a structured cover page for the EUDR audit report."""
    pdf.set_font("Helvetica", "B", 22)
    pdf.ln(30)
    pdf.cell(0, 14, "EUDR Satellite Evidence Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, f"Report reference: {instance_id}", align="C", new_x="LMARGIN", new_y="NEXT")
    enriched_at = manifest.get("enriched_at", "")
    if enriched_at:
        pdf.cell(0, 7, f"Generated: {enriched_at[:19]}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Operator info (if available)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 11)
    operator = manifest.get("operator_name", "")
    if operator:
        pdf.cell(
            0, 7, f"Operator: {_safe_text(operator)}", align="C", new_x="LMARGIN", new_y="NEXT"
        )
    commodity = manifest.get("commodity", "")
    if commodity:
        pdf.cell(
            0, 7, f"Commodity: {_safe_text(commodity)}", align="C", new_x="LMARGIN", new_y="NEXT"
        )

    # Summary counts
    per_aoi = manifest.get("per_aoi_enrichment", [])
    total = len(per_aoi)
    succeeded = [a for a in per_aoi if "error" not in a]
    free_count = sum(
        1 for a in succeeded if a.get("determination", {}).get("status") == "deforestation_free"
    )
    review_count = len(succeeded) - free_count

    pdf.ln(8)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, f"Production plots assessed: {total}", align="C", new_x="LMARGIN", new_y="NEXT")
    if succeeded:
        pdf.cell(
            0,
            7,
            f"Deforestation-free: {free_count} | Further review: {review_count}",
            align="C",
            new_x="LMARGIN",
            new_y="NEXT",
        )

    cutoff = manifest.get("eudr_date_start", EUDR_CUTOFF_DATE)
    pdf.cell(
        0,
        7,
        f"Assessment period: {cutoff} to present",
        align="C",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0,
        6,
        "Generated by Canopex satellite analysis platform",
        align="C",
        new_x="LMARGIN",
        new_y="NEXT",
    )


def _audit_executive_summary(pdf: Any, manifest: dict[str, Any]) -> None:
    """Write executive summary section."""
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "1. Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)

    per_aoi = manifest.get("per_aoi_enrichment", [])
    succeeded = [a for a in per_aoi if "error" not in a]
    failed = [a for a in per_aoi if "error" in a]
    free_count = sum(
        1 for a in succeeded if a.get("determination", {}).get("status") == "deforestation_free"
    )
    review_count = len(succeeded) - free_count

    pdf.cell(0, 6, f"Total plots assessed: {len(per_aoi)}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0,
        6,
        f"Plots classified deforestation-free: {free_count} of {len(succeeded)}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    if review_count:
        pdf.cell(
            0,
            6,
            f"Plots requiring further review: {review_count}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
    if failed:
        pdf.cell(
            0,
            6,
            f"Plots with enrichment errors: {len(failed)}",
            new_x="LMARGIN",
            new_y="NEXT",
        )

    pdf.ln(3)
    pdf.cell(0, 6, "Data sources:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(
        0,
        5,
        "  - Sentinel-2 L2A (10m, via Microsoft Planetary Computer)",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(0, 5, "  - ESA WorldCover 10m (2021)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "  - WDPA (World Database on Protected Areas)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0,
        5,
        "  - IO Annual Land Use / Land Cover (2017-2023)",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(0, 5, "  - ALOS PALSAR Forest/Non-Forest", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)


def _audit_methodology(pdf: Any) -> None:
    """Write methodology section."""
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "2. Methodology", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)

    sections = [
        (
            "Satellite imagery",
            "Sentinel-2 Level-2A surface reflectance imagery at 10m spatial resolution, "
            "sourced via Microsoft Planetary Computer STAC API. Cloud-masked using the "
            "SCL (Scene Classification Layer) band.",
        ),
        (
            "Vegetation index",
            "NDVI (Normalized Difference Vegetation Index) computed from Sentinel-2 "
            "bands B08 (NIR) and B04 (Red). NDVI values range from -1 to +1; healthy "
            "vegetation typically exceeds 0.4.",
        ),
        (
            "Change detection",
            "Season-matched year-over-year NDVI comparison. Each observation period is "
            "compared to the same season in the preceding year. Loss is flagged when NDVI "
            "decline exceeds the deforestation threshold across a significant portion of "
            "the parcel.",
        ),
        (
            "Baseline reference",
            "The EUDR cutoff date is 31 December 2020. Imagery from the first available "
            "post-cutoff observation period serves as the baseline. All subsequent periods "
            "are compared against this baseline and against each other.",
        ),
        (
            "Land cover classification",
            "ESA WorldCover 10m (2021) provides baseline land-cover class (tree cover, "
            "cropland, grassland, etc.) at the time closest to the EUDR cutoff date.",
        ),
        (
            "Protected areas",
            "WDPA (World Database on Protected Areas) is checked for spatial overlap "
            "with each parcel. Overlap with a protected area is flagged as a risk factor.",
        ),
        (
            "Deforestation determination",
            "A parcel is classified 'deforestation_free' when: (1) no significant NDVI "
            "loss (>5% of area or >1 ha) is detected in any post-2020 comparison period, "
            "and (2) the overall vegetation trajectory is not declining. Otherwise the "
            "parcel is classified 'further_review'.",
        ),
        (
            "Limitations",
            "Cloud cover may reduce temporal coverage. Mixed pixels at parcel boundaries "
            "can affect NDVI accuracy. Sentinel-2 revisit interval is 5 days at the "
            "equator. NDVI is a proxy for vegetation health, not a direct measure of "
            "tree count or biomass. This analysis provides supporting evidence only.",
        ),
    ]

    for title, body in sections:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 4, body)
        pdf.ln(2)

    pdf.ln(2)


def _render_parcel_review_section(
    pdf: Any,
    review: "dict[str, Any] | None",
    history: "list[dict[str, Any]] | None" = None,
) -> None:
    """Append the human-review audit trail block to a PDF parcel section.

    When ``history`` is provided and contains more than one revision the full
    audit history is rendered in chronological order so the PDF shows every
    decision, not just the most recent one.  The block is rendered in amber so
    it stands out visually from the algorithmic findings.
    """
    revisions: list[dict] = list(history) if isinstance(history, list) else []
    # Fall back to the latest-state record when no detailed history is stored.
    if not revisions and isinstance(review, dict) and review.get("note"):
        revisions = [{"action": "save", **review}]

    if not revisions:
        return

    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(180, 100, 0)
    if len(revisions) == 1:
        single = revisions[0]
        label = (
            "Human-reviewed \u2014 compliance accepted with explanation"
            if single.get("override")
            else "Human review note attached"
        )
        pdf.cell(0, 6, _safe_text(label), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(0, 0, 0)
        note = single.get("note", "")
        if note:
            pdf.multi_cell(0, 5, _safe_text(f"Note: {note}"))
        reviewed_by = single.get("reviewed_by", "")
        reviewed_at = single.get("reviewed_at", "")
        if reviewed_by or reviewed_at:
            at_str = reviewed_at[:19] if reviewed_at else ""
            pdf.cell(
                0,
                5,
                _safe_text(f"Reviewer: {reviewed_by}  |  Reviewed at: {at_str}"),
                new_x="LMARGIN",
                new_y="NEXT",
            )
    else:
        pdf.cell(0, 6, "Human review audit history (all revisions)", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(0, 0, 0)
        for i, rev in enumerate(revisions, start=1):
            action = rev.get("action", "save")
            reviewed_by = rev.get("reviewed_by", "")
            reviewed_at = rev.get("reviewed_at", "")
            at_str = reviewed_at[:19] if reviewed_at else ""
            if action == "revert":
                summary = f"Revision {i}: Reverted to algorithmic — {reviewed_by} at {at_str}"
            elif rev.get("override"):
                summary = f"Revision {i}: Compliant with explanation — {reviewed_by} at {at_str}"
            else:
                summary = f"Revision {i}: Note attached — {reviewed_by} at {at_str}"
            pdf.cell(0, 5, _safe_text(summary), new_x="LMARGIN", new_y="NEXT")
            note = rev.get("note", "")
            if note:
                pdf.multi_cell(0, 4, _safe_text(f"    Note: {note}"))


def _audit_single_parcel(
    pdf: Any,
    aoi: dict[str, Any],
    section_num: str,
    review: dict[str, Any] | None = None,
    review_history: list[dict[str, Any]] | None = None,
) -> None:
    """Write a single parcel's assessment in the audit report.

    When ``review_history`` is provided the full audit history is rendered so
    every revision is visible in the PDF.  When only ``review`` is available the
    latest-state record is shown as a single-revision block.  When neither is
    present no review section is emitted.
    """
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(
        0,
        8,
        _safe_text(f"{section_num} {aoi.get('name', 'Parcel')}"),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_font("Helvetica", "", 9)

    # Location and area
    area = aoi.get("area_ha", 0.0)
    center = aoi.get("center", {})
    coords = aoi.get("coords", [])
    pdf.cell(
        0,
        5,
        f"Area: {area:.2f} ha | Centre: "
        f"{center.get('lat', 0):.6f}, {center.get('lon', 0):.6f} | "
        f"Vertices: {len(coords)}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    # Determination result
    det = aoi.get("determination", {})
    status = det.get("status", "unknown")
    confidence = det.get("confidence", "unknown")
    pdf.set_font("Helvetica", "B", 10)
    status_label = {
        "deforestation_free": "DEFORESTATION-FREE",
        "further_review": "FURTHER REVIEW REQUIRED",
    }.get(status, status.upper())
    pdf.cell(
        0,
        7,
        f"Determination: {status_label} (confidence: {confidence})",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_font("Helvetica", "", 9)

    for flag in det.get("flags", []):
        pdf.set_text_color(180, 0, 0)
        pdf.cell(0, 5, _safe_text(f"  ! {flag}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)

    # WorldCover baseline
    wc = aoi.get("worldcover", {})
    if wc.get("available"):
        lc = wc.get("land_cover", {})
        pdf.cell(
            0,
            5,
            f"Land cover (WorldCover 2021): {lc.get('dominant_class', 'N/A')} (dominant)",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        for cls in lc.get("classes", [])[:5]:
            label = cls.get("label", "")
            pct = cls.get("area_pct")
            pct_str = f"{float(pct):.1f}%" if pct is not None else "N/A"
            pdf.cell(0, 4, f"    {label}: {pct_str}", new_x="LMARGIN", new_y="NEXT")

    # Protected area
    wdpa = aoi.get("wdpa", {})
    if wdpa.get("checked"):
        prot = "YES -- overlap detected" if wdpa.get("is_protected") else "No overlap"
        pdf.cell(0, 5, f"Protected area (WDPA): {prot}", new_x="LMARGIN", new_y="NEXT")

    # NDVI timeseries
    ndvi_stats = aoi.get("ndvi_stats", [])
    frame_plan = aoi.get("frame_plan", [])
    valid = [s for s in ndvi_stats if s and s.get("mean") is not None]
    if valid:
        means = [s["mean"] for s in valid]
        pdf.cell(
            0,
            5,
            f"NDVI: {len(valid)} observations | "
            f"Latest: {means[-1]:.3f} | Range: {min(means):.3f}-{max(means):.3f}",
            new_x="LMARGIN",
            new_y="NEXT",
        )

    # Change detection
    cd_summary = aoi.get("change_detection", {}).get("summary", {})
    if cd_summary:
        pdf.cell(
            0,
            5,
            f"Change trajectory: {cd_summary.get('trajectory', 'unknown')} "
            f"({cd_summary.get('comparisons', 0)} comparisons)",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        loss = cd_summary.get("total_loss_ha")
        gain = cd_summary.get("total_gain_ha")
        if loss is not None or gain is not None:
            pdf.cell(
                0,
                5,
                f"  Loss: {loss or 0:.2f} ha | Gain: {gain or 0:.2f} ha",
                new_x="LMARGIN",
                new_y="NEXT",
            )

    # Data provenance (scene IDs)
    scenes = []
    for i, stat in enumerate(ndvi_stats):
        if stat and stat.get("scene_id"):
            label = frame_plan[i].get("label", f"Frame {i}") if i < len(frame_plan) else ""
            scenes.append(f"{label}: {stat['scene_id']}")
    if scenes:
        pdf.cell(0, 5, "Scene provenance:", new_x="LMARGIN", new_y="NEXT")
        for scene in scenes[:10]:
            pdf.cell(0, 4, f"    {scene}", new_x="LMARGIN", new_y="NEXT")

    # Human review audit trail — printed only when a reviewer submitted an assessment
    _render_parcel_review_section(pdf, review, history=review_history)

    pdf.ln(4)


def _audit_per_parcel(
    pdf: Any,
    per_aoi: list[dict[str, Any]],
    parcel_reviews: dict[str, Any] | None = None,
    parcel_review_history: dict[str, Any] | None = None,
) -> None:
    """Write detailed per-parcel assessment sections."""
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "3. Per-Parcel Assessment", new_x="LMARGIN", new_y="NEXT")

    for idx, aoi in enumerate(per_aoi):
        name = aoi.get("name", f"Parcel {idx + 1}")
        section_num = f"3.{idx + 1}"

        if "error" in aoi:
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(
                0,
                8,
                _safe_text(f"{section_num} {name} -- ENRICHMENT FAILED"),
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(
                0,
                5,
                "Data enrichment failed for this parcel. No assessment available.",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.ln(4)
            continue

        review = _as_dict(parcel_reviews).get(str(idx))
        history = _as_dict(parcel_review_history).get(str(idx))
        _audit_single_parcel(pdf, aoi, section_num, review=review, review_history=history)


def _audit_appendix(
    pdf: Any,
    manifest: dict[str, Any],
) -> None:
    """Write appendix with post-2020 NDVI timeseries table."""
    frame_plan = manifest.get("frame_plan", [])
    ndvi_stats = manifest.get("ndvi_stats", [])

    # Filter to post-2020 only
    filtered: list[tuple[dict, dict | None]] = []
    for i, frame in enumerate(frame_plan):
        year = frame.get("year", 0)
        if year >= _EUDR_CUTOFF_YEAR:
            ndvi = ndvi_stats[i] if i < len(ndvi_stats) else None
            filtered.append((frame, ndvi))

    if not filtered:
        return

    pdf.add_page()
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "4. Appendix: Post-2020 NDVI Timeseries", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 8)
    col_ratios = [0.14, 0.09, 0.09, 0.12, 0.12, 0.10, 0.10, 0.10, 0.14]
    page_w = pdf.epw
    col_widths = [round(r * page_w, 1) for r in col_ratios]
    headers_row = [
        "Label",
        "Year",
        "Season",
        "Start",
        "End",
        "NDVI Mean",
        "NDVI Min",
        "NDVI Max",
        "Scene ID",
    ]
    for i, h in enumerate(headers_row):
        pdf.cell(col_widths[i], 6, h, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 7)
    for frame, ndvi in filtered:
        ndvi_mean = f"{ndvi['mean']:.3f}" if ndvi and ndvi.get("mean") is not None else "--"
        ndvi_min = f"{ndvi['min']:.3f}" if ndvi and ndvi.get("min") is not None else "--"
        ndvi_max = f"{ndvi['max']:.3f}" if ndvi and ndvi.get("max") is not None else "--"
        scene_id = (ndvi.get("scene_id", "") if ndvi else "")[:16]

        row_data = [
            _safe_text(frame.get("label", ""))[:16],
            str(frame.get("year", "")),
            frame.get("season", ""),
            frame.get("start", ""),
            frame.get("end", ""),
            ndvi_mean,
            ndvi_min,
            ndvi_max,
            scene_id,
        ]
        for i, val in enumerate(row_data):
            pdf.cell(col_widths[i], 5, val, border=1)
        pdf.ln()

    pdf.ln(4)


def _audit_disclaimer(pdf: Any) -> None:
    """Write legal disclaimer for the audit report."""
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "Legal Disclaimer", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(
        0,
        4,
        "This report provides satellite-based evidence to support EUDR due diligence "
        "under Regulation (EU) 2023/1115. It does not constitute a complete Due Diligence "
        "Statement (DDS). Operators remain responsible for fulfilling all regulatory "
        "obligations including risk assessment, mitigation measures, and submission of "
        "the DDS to the EU Information System.\n\n"
        "The analysis is based on publicly available satellite imagery and geospatial "
        "datasets. Results are subject to the limitations of remote sensing including "
        "cloud cover, sensor resolution, and mixed-pixel effects. All NDVI and change "
        "detection results should be interpreted as supporting evidence, not definitive "
        "proof of land-use status.\n\n"
        "Methodology: Sentinel-2 L2A via Microsoft Planetary Computer; NDVI change "
        "detection; ESA WorldCover 2021; WDPA protected area overlay; IO Annual LULC; "
        "ALOS PALSAR Forest/Non-Forest.",
    )


def build_eudr_audit_pdf(
    manifest: dict[str, Any],
    instance_id: str = "",
    parcel_reviews: dict[str, Any] | None = None,
    parcel_review_history: dict[str, Any] | None = None,
) -> bytes:
    """Build an audit-grade EUDR evidence PDF report (#587).

    Structured for compliance officers: cover page, executive summary,
    methodology, per-parcel assessment, post-2020 NDVI appendix, and
    legal disclaimer.

    When ``parcel_review_history`` is provided (keyed by string AOI index),
    each parcel section renders the full immutable revision history so auditors
    can see every decision, not just the most recent one.  ``parcel_reviews``
    is used as a fallback when history is absent (backward-compatible).
    """
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # 1. Cover page
    pdf.add_page()
    _audit_cover_page(pdf, manifest, instance_id)

    # 2. Executive summary
    pdf.add_page()
    _audit_executive_summary(pdf, manifest)

    # 3. Methodology
    _audit_methodology(pdf)

    # 4. Per-parcel assessment
    per_aoi = manifest.get("per_aoi_enrichment", [])
    if per_aoi:
        pdf.add_page()
        _audit_per_parcel(
            pdf,
            per_aoi,
            parcel_reviews=parcel_reviews,
            parcel_review_history=parcel_review_history,
        )

    # 5. Appendix: post-2020 NDVI timeseries
    _audit_appendix(pdf, manifest)

    # 6. Legal disclaimer
    _audit_disclaimer(pdf)

    return bytes(pdf.output())
