"""Tests for Dockerfile container image build configuration.

Validates that the Dockerfile correctly builds a containerized Azure Functions
app with Python v2 programming model requirements for Azure Container Apps:

1. Avoids manual Microsoft APT repository setup that can conflict with base
    image package sources.

2. Copies function app files (function_app.py, host.json, kml_satellite/)
   to builder stage for packaging into runtime image.

3. Python v2 function metadata (.azurefunctions/) is auto-generated by the
   Azure Functions runtime at startup. No build-time generation is needed.

4. Includes GDAL and geospatial libraries for KML/raster processing.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

DOCKERFILE_PATH = Path(__file__).resolve().parent.parent.parent / "Dockerfile"


@pytest.fixture(scope="module")
def dockerfile_content() -> str:
    """Read Dockerfile content as string."""
    assert DOCKERFILE_PATH.exists(), f"Dockerfile not found at {DOCKERFILE_PATH}"
    return DOCKERFILE_PATH.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Test: Multi-stage build structure
# ---------------------------------------------------------------------------


class TestMultiStageBuild:
    """Verify Dockerfile uses multi-stage build for smaller runtime image."""

    def test_has_builder_stage(self, dockerfile_content: str) -> None:
        """Dockerfile must have a builder stage."""
        assert "FROM " in dockerfile_content
        assert " AS builder" in dockerfile_content, (
            "Dockerfile must have a builder stage for compilation/metadata generation"
        )

    def test_has_runtime_stage(self, dockerfile_content: str) -> None:
        """Dockerfile must have a separate runtime stage."""
        lines = dockerfile_content.split("\n")
        from_count = sum(1 for line in lines if line.strip().startswith("FROM "))
        assert from_count >= 2, "Dockerfile must have at least 2 FROM statements (multi-stage)"

    def test_uses_azure_functions_base_image(self, dockerfile_content: str) -> None:
        """Dockerfile must use official Azure Functions Python base image."""
        assert "mcr.microsoft.com/azure-functions/python:4-python3.12" in dockerfile_content, (
            "Dockerfile must use mcr.microsoft.com/azure-functions/python:4-python3.12 base image"
        )

    def test_runtime_stage_runs_as_non_root(self, dockerfile_content: str) -> None:
        """Runtime stage should run as non-root app user."""
        lines = dockerfile_content.split("\n")
        runtime_section = []
        in_runtime = False

        for line in lines:
            if in_runtime:
                runtime_section.append(line)
            elif line.strip().startswith("FROM ") and " AS builder" not in line:
                in_runtime = True

        runtime_text = "\n".join(runtime_section)
        assert "USER app" in runtime_text, "Runtime stage must switch to non-root user 'app'"


# ---------------------------------------------------------------------------
# Test: APT repository safety
# ---------------------------------------------------------------------------


class TestAptRepositorySafety:
    """Ensure Dockerfile avoids duplicate/conflicting Microsoft APT sources."""

    def test_no_manual_microsoft_repo_setup(self, dockerfile_content: str) -> None:
        """Dockerfile must not manually add Microsoft package repositories/keys."""
        assert "microsoft-archive-keyring.gpg" not in dockerfile_content, (
            "Dockerfile must not add microsoft-archive-keyring.gpg"
        )
        assert "microsoft-prod.list" not in dockerfile_content, (
            "Dockerfile must not create /etc/apt/sources.list.d/microsoft-prod.list"
        )
        assert "packages.microsoft.com/keys/microsoft.asc" not in dockerfile_content, (
            "Dockerfile must not fetch Microsoft apt key manually"
        )
        assert "azure-functions-core-tools-4" not in dockerfile_content, (
            "Dockerfile should not install Core Tools; runtime discovers Python v2 functions"
        )


# ---------------------------------------------------------------------------
# Test: Python v2 function metadata generation
# ---------------------------------------------------------------------------


class TestFunctionMetadataGeneration:
    """Verify that Dockerfile properly sets up Python v2 function app.

    Python v2 Azure Functions auto-generate .azurefunctions/ metadata at
    runtime when the Functions host initializes. No build-time metadata
    generation is needed (unlike Python v1 which required explicit build).
    """

    def test_copies_function_app_files_to_builder(self, dockerfile_content: str) -> None:
        """Builder stage must copy function app files for packaging."""
        lines = dockerfile_content.split("\n")

        # Find builder stage start
        builder_start = None
        for idx, line in enumerate(lines):
            if " AS builder" in line:
                builder_start = idx
                break

        assert builder_start is not None

        # Find end of builder stage (next FROM statement)
        builder_end = None
        for idx in range(builder_start + 1, len(lines)):
            if lines[idx].strip().startswith("FROM ") and " AS builder" not in lines[idx]:
                builder_end = idx
                break

        if builder_end is None:
            builder_end = len(lines)

        builder_section = "\n".join(lines[builder_start:builder_end])

        # Must copy function_app.py, host.json, and kml_satellite/
        assert "function_app.py" in builder_section, (
            "Builder stage must copy function_app.py for packaging"
        )
        assert "host.json" in builder_section, "Builder stage must copy host.json"
        assert "kml_satellite" in builder_section, "Builder stage must copy kml_satellite/ package"

    def test_copies_application_to_runtime(self, dockerfile_content: str) -> None:
        """Runtime stage must copy application files from builder."""
        lines = dockerfile_content.split("\n")
        runtime_section = []
        in_runtime = False

        for line in lines:
            if in_runtime:
                runtime_section.append(line)
            elif line.strip().startswith("FROM ") and " AS builder" not in line:
                in_runtime = True

        runtime_text = "\n".join(runtime_section)

        # Runtime must copy application files from builder
        assert "COPY --from=builder" in runtime_text, "Runtime stage must copy files from builder"
        assert "function_app.py" in runtime_text, "Runtime stage must copy function_app.py"
        assert "kml_satellite" in runtime_text, "Runtime stage must copy kml_satellite/ package"

    def test_no_broken_func_build_command(self, dockerfile_content: str) -> None:
        """Dockerfile must not use non-existent 'func build --python' command.

        Azure Functions Core Tools v4 does not support 'func build' subcommand.
        Python v2 metadata is auto-generated at runtime by Functions host.
        """
        lines = dockerfile_content.split("\n")

        for idx, line in enumerate(lines):
            if "func build" in line and line.strip().startswith("RUN"):
                # This line should not exist
                raise AssertionError(
                    f"Line {idx + 1}: Dockerfile contains 'func build' command which does not "
                    f"exist in Core Tools v4. Python v2 metadata is auto-generated at runtime.\n"
                    f"Line: {line}"
                )


# ---------------------------------------------------------------------------
# Test: GDAL and geospatial dependencies
# ---------------------------------------------------------------------------


class TestGeospatialDependencies:
    """Verify GDAL/GEOS/PROJ libraries for KML/raster processing."""

    def test_installs_gdal_dev_in_builder(self, dockerfile_content: str) -> None:
        """Builder stage must install libgdal-dev for building rasterio/Fiona."""
        assert "libgdal-dev" in dockerfile_content, (
            "Builder stage must install libgdal-dev for building geospatial wheels"
        )

    def test_runtime_avoids_gdal_bin(self, dockerfile_content: str) -> None:
        """Runtime stage should avoid heavyweight gdal-bin package."""
        lines = dockerfile_content.split("\n")
        runtime_section = []
        in_runtime = False

        for line in lines:
            if in_runtime:
                runtime_section.append(line)
            elif line.strip().startswith("FROM ") and " AS builder" not in line:
                in_runtime = True

        runtime_pkg_lines = [line.strip() for line in runtime_section if line.strip()]
        installs_gdal_bin = any(line.startswith("gdal-bin") for line in runtime_pkg_lines)
        assert not installs_gdal_bin, (
            "Runtime stage should not install gdal-bin; geospatial wheels include native libs"
        )

    def test_runtime_has_import_smoke_check(self, dockerfile_content: str) -> None:
        """Dockerfile should fail build early if native deps are unresolved."""
        assert 'RUN python -c "import rasterio, fiona, pyproj, shapely"' in dockerfile_content, (
            "Dockerfile must include geospatial import smoke check"
        )

    def test_prunes_python_cache_artifacts(self, dockerfile_content: str) -> None:
        """Runtime image should prune pycache/bytecode from packaged deps and app code."""
        assert "--no-compile --target=/home/site/wwwroot/.python_packages/lib/site-packages" in (
            dockerfile_content
        ), "Dockerfile should disable bytecode compilation during pip install"
        assert "-type d -name '__pycache__'" in dockerfile_content, (
            "Dockerfile should remove __pycache__ directories from packaged artifacts"
        )
        assert "-name '*.pyc' -o -name '*.pyo'" in dockerfile_content, (
            "Dockerfile should remove compiled Python bytecode files from packaged artifacts"
        )

    def test_sets_gdal_config_env(self, dockerfile_content: str) -> None:
        """Builder must set GDAL_CONFIG for pip to find GDAL during wheel builds."""
        assert "GDAL_CONFIG" in dockerfile_content, (
            "Dockerfile must set GDAL_CONFIG environment variable for pip"
        )
        assert "gdal-config" in dockerfile_content, "GDAL_CONFIG must point to gdal-config binary"
